/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DesafioRouteImport } from './routes/desafio'
import { Route as LogrosRouteImport } from './routes/logros'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PlayRouteImport } from './routes/play'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as PlayIndexRouteImport } from './routes/play.index'
import { Route as PlayGameIdRouteImport } from './routes/play.$gameId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DesafioRoute = DesafioRouteImport.update({
  id: '/desafio',
  path: '/desafio',
  getParentRoute: () => rootRouteImport,
} as any)
const LogrosRoute = LogrosRouteImport.update({
  id: '/logros',
  path: '/logros',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayIndexRoute = PlayIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlayRoute,
} as any)
const PlayGameIdRoute = PlayGameIdRouteImport.update({
  id: '/$gameId',
  path: '/$gameId',
  getParentRoute: () => PlayRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/desafio': typeof DesafioRoute
  '/logros': typeof LogrosRoute
  '/perfil': typeof PerfilRoute
  '/play': typeof PlayRouteWithChildren
  '/ranking': typeof RankingRoute
  '/play/$gameId': typeof PlayGameIdRoute
  '/play/': typeof PlayIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/desafio': typeof DesafioRoute
  '/logros': typeof LogrosRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
  '/play/$gameId': typeof PlayGameIdRoute
  '/play': typeof PlayIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/desafio': typeof DesafioRoute
  '/logros': typeof LogrosRoute
  '/perfil': typeof PerfilRoute
  '/play': typeof PlayRouteWithChildren
  '/ranking': typeof RankingRoute
  '/play/$gameId': typeof PlayGameIdRoute
  '/play/': typeof PlayIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/desafio'
    | '/logros'
    | '/perfil'
    | '/play'
    | '/ranking'
    | '/play/$gameId'
    | '/play/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/desafio'
    | '/logros'
    | '/perfil'
    | '/ranking'
    | '/play/$gameId'
    | '/play'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/desafio'
    | '/logros'
    | '/perfil'
    | '/play'
    | '/ranking'
    | '/play/$gameId'
    | '/play/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DesafioRoute: typeof DesafioRoute
  LogrosRoute: typeof LogrosRoute
  PerfilRoute: typeof PerfilRoute
  PlayRoute: typeof PlayRouteWithChildren
  RankingRoute: typeof RankingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desafio': {
      id: '/desafio'
      path: '/desafio'
      fullPath: '/desafio'
      preLoaderRoute: typeof DesafioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logros': {
      id: '/logros'
      path: '/logros'
      fullPath: '/logros'
      preLoaderRoute: typeof LogrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/': {
      id: '/play/'
      path: '/'
      fullPath: '/play/'
      preLoaderRoute: typeof PlayIndexRouteImport
      parentRoute: typeof PlayRoute
    }
    '/play/$gameId': {
      id: '/play/$gameId'
      path: '/$gameId'
      fullPath: '/play/$gameId'
      preLoaderRoute: typeof PlayGameIdRouteImport
      parentRoute: typeof PlayRoute
    }
  }
}

interface PlayRouteChildren {
  PlayGameIdRoute: typeof PlayGameIdRoute
  PlayIndexRoute: typeof PlayIndexRoute
}

const PlayRouteChildren: PlayRouteChildren = {
  PlayGameIdRoute: PlayGameIdRoute,
  PlayIndexRoute: PlayIndexRoute,
}

const PlayRouteWithChildren = PlayRoute._addFileChildren(PlayRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DesafioRoute: DesafioRoute,
  LogrosRoute: LogrosRoute,
  PerfilRoute: PerfilRoute,
  PlayRoute: PlayRouteWithChildren,
  RankingRoute: RankingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
